# Generated by Django 2.2.5 on 2019-10-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191006_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(null=True, verbose_name='内容HTML格式'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_markdown',
            field=models.BooleanField(default=True, verbose_name='使用MarkDown格式'),
        ),
    ]
