# Generated by Django 2.2.5 on 2019-10-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20191010_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.CharField(max_length=200, null=True, verbose_name='评论目标'),
        ),
    ]
